/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mugui.struts.action;

import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONObject;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.alipay.api.AlipayApiException;
import com.alipay.api.internal.util.AlipaySignature;
import com.alipay.util.AlipayCore;
import com.mugui.http.Bean.AliPayBean;
import com.mugui.http.Bean.AliPublicBean;
import com.mugui.model.PayModel;

/**
 * MyEclipse Struts Creation date: 12-06-2016
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class AccpetaliAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		response.setHeader("Access-Control-Allow-Origin", "*");
		response.setHeader("Access-Control-Allow-Methods", "POST,GET");
		response.setContentType("text/html;charset=utf-8");
		response.setCharacterEncoding("utf-8");
		Map<String, String[]> e = request.getParameterMap();
		Iterator<Entry<String, String[]>> set = e.entrySet().iterator();
		Entry<String, String[]> entry = null;
		JSONObject jsonObject = new JSONObject();
		while (set.hasNext()) {
			entry = set.next();
			String name = entry.getKey();
			jsonObject.put(name, request.getParameter(name));
		}
		Map<String, String> map = AlipayCore.JSON2Map(jsonObject);
		try {
			AliPublicBean bean = new AliPublicBean();
			boolean b = AlipaySignature.rsaCheckV1(map, bean.Refund_Public_key, bean.getCharset(), bean.getSign_type());
		
			if (b) {
				PayModel.newPay(response, new AliPayBean(jsonObject));  
			}
		} catch (AlipayApiException e1) {
			e1.printStackTrace();
		}
		return null;

	}
}